version: 2

models:
  # ============================================
  # Витрина 1: Цена по дням до вылета
  # ============================================
  - name: dm_price_by_days_before_departure
    description: "Средняя цена билета в зависимости от того, за сколько дней до вылета он был найден"

    columns:
      - name: days_until_departure
        description: "За сколько дней до вылета был спарсен билет"
        tests:
          - unique
          - not_null

      - name: avg_price
        description: "Средняя цена билета (руб)"
        tests:
          - not_null

      - name: min_price
        description: "Минимальная цена"

      - name: max_price
        description: "Максимальная цена"

      - name: observations_count
        description: "Количество наблюдений"
        tests:
          - not_null

      - name: price_rank
        description: "Рейтинг (1 = лучший день для покупки)"


  # ============================================
  # Витрина 2: Цена по времени парсинга
  # ============================================
  - name: dm_price_by_fetch_time
    description: "Средняя цена билета по дню недели и часу парсинга"

    columns:
      - name: fetch_day_of_week
        description: "День недели (0=Вс, 1=Пн, ..., 6=Сб)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]

      - name: fetch_hour
        description: "Час парсинга (0-23)"
        tests:
          - not_null

      - name: day_name
        description: "Название дня недели"

      - name: avg_price
        description: "Средняя цена (руб)"
        tests:
          - not_null

      - name: observations_count
        description: "Количество наблюдений"

      - name: price_rank
        description: "Рейтинг (1 = лучшее время)"


  # ============================================
  # Витрина 3: Лучшие цены на рейс
  # ============================================
  - name: dm_best_prices_per_flight
    description: "Минимальная зафиксированная цена на каждый рейс с контекстом"

    columns:
      - name: flight_price_id
        description: "ID рейса из API"
        tests:
          - unique
          - not_null
          # Тест relationships - проверяем что ID есть в ODS
          - relationships:
              to: ref('ods_flight_prices')
              field: flight_price_id

      - name: airline
        description: "Код авиакомпании"
        tests:
          - not_null

      - name: flight_number
        description: "Номер рейса"

      - name: departure_at
        description: "Дата и время вылета"
        tests:
          - not_null

      - name: best_price
        description: "Лучшая (минимальная) цена на рейс"
        tests:
          - not_null

      - name: best_price_found_at
        description: "Когда была найдена лучшая цена"

      - name: times_seen
        description: "Сколько раз мы видели этот рейс"

      - name: price_spread
        description: "Разброс цен (max - min)"

      - name: potential_savings
        description: "Экономия при покупке по лучшей цене vs средней"
