version: 2

models:
  # ============================================
  # Витрина 1: За сколько дней до вылета покупать
  # ============================================
  - name: dm_price_by_days_before_departure
    description: >
      Анализ влияния срока покупки на цену билета.
      Ключевая метрика — avg_price_deviation: среднее отклонение цены от средней цены рейса.
      Отрицательное значение = в этот период цены НИЖЕ средней.

      Материализация: incremental (merge по days_until_departure)

    columns:
      - name: days_until_departure
        description: "За сколько дней до вылета (0-90)"
        tests:
          - not_null
          - unique

      - name: avg_price_deviation
        description: "Отклонение от средней цены рейса (руб). Отрицательное = дешевле."
        tests:
          - not_null

      - name: avg_price
        description: "Средняя абсолютная цена (руб)"
        tests:
          - not_null

      - name: min_price
        description: "Минимальная цена"

      - name: max_price
        description: "Максимальная цена"

      - name: observations_count
        description: "Количество наблюдений"
        tests:
          - not_null

      - name: price_rank
        description: "Рейтинг (1 = лучший период для покупки)"

      - name: last_observation
        description: "Временная метка последнего наблюдения для этого периода (для инкрементальной загрузки)"
        tests:
          - not_null


  # ============================================
  # Витрина 2: В какое время искать билеты
  # ============================================
  - name: dm_price_by_day_and_hour
    description: >
      Анализ влияния времени парсинга на цену билета.
      Группировка: день недели + час.
      Ключевая метрика — avg_price_deviation: среднее отклонение цены от средней цены рейса.
      Для агрегации по дню или часу — используйте GROUP BY в запросе.

    columns:
      - name: fetch_day_of_week
        description: "День недели парсинга (0=Вс, 1=Пн, ..., 6=Сб)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]

      - name: fetch_hour
        description: "Час парсинга (0-23)"
        tests:
          - not_null

      - name: day_name
        description: "Название дня недели"

      - name: avg_price_deviation
        description: "Отклонение от средней цены рейса (руб). Отрицательное = дешевле."
        tests:
          - not_null

      - name: avg_price
        description: "Средняя абсолютная цена (руб)"
        tests:
          - not_null

      - name: min_price
        description: "Минимальная цена"

      - name: max_price
        description: "Максимальная цена"

      - name: observations_count
        description: "Количество наблюдений"

      - name: price_rank
        description: "Рейтинг (1 = лучшее время для поиска)"
